export const SET_MODAL_CONTENT = "SET_MODAL_CONTENT";
export const SET_MODAL_VIEW_STATE = "SET_MODAL_VIEW_STATE";
export const INGREDIENT_MODAL_TYPE = "INGREDIENT_MODAL_TYPE";
export const ORDER_MODAL_TYPE = "ORDER_MODAL_TYPE";
