import { HomePage } from './home/home';
import { LoginPage } from './login/login';
import { RegisterPage } from './register/register';
import { ForgotPasswordPage } from './forgot-password/forgot-password';
import { ResetPasswordPage } from './reset-password/reset-password';
import { ProfilePage } from './profile/profile';
import { ProfileOrdersControl } from './profile/orders/profile_orders';
import { ProfileOrdersIdControl } from './profile/orders/id/profile_order__id';
import { NotFound404 } from './NotFound404/NotFound404';
import { FeedPage } from './feed/feed';
export { HomePage, LoginPage, RegisterPage, ResetPasswordPage, ForgotPasswordPage, ProfilePage, ProfileOrdersControl, ProfileOrdersIdControl, NotFound404, FeedPage };